### PR TITLE
feat: collision events include both affected objects' data

### PR DESCRIPTION
**Pull request by RodrigoHamuy**
Why?

If you want to get data from both objects affected on a collision event, you can only access the data of "the other" object, and you need to use `useRef` in order to access the object firing the event.

Example:

```jsx
const ref  = useRef(null);

return <RigidBody  onCollisionEnter={e => {
  console.log(ref.current!.translation()); // object firing event
  console.log(e.rigidBody!.translation()) // the other object of the interaction
} />
```

To avoid having to depend on an `useRef`, this PR includes the firing rigid body data too, so you can instead do this:

```jsx
<RigidBody onCollisionEnter={e => {
  console.log(e.target.rigidBody!.translation()); // object firing event
  console.log(e.other.rigidBody!.translation()) // the other object of the interaction
} />
```

The types previously were:

```tsx
export type BaseCollisionPayload = {
  rigidBody?: RapierRigidBody;
  collider: RapierCollider;
  rigidBodyObject?: Object3D;
  colliderObject?: Object3D;
};
```

And now is:

```tsx
export type BaseCollisionObject = {
  rigidBody?: RapierRigidBody;
  collider: RapierCollider;
  rigidBodyObject?: Object3D;
  colliderObject?: Object3D;
}

export type BaseCollisionPayload = {
  /** the object firing the event */
  target: BaseCollisionObject;
  /** the other object involved in the event */
  other: BaseCollisionObject;
  /** deprecated use `other.rigidBody` instead */
  rigidBody?: RapierRigidBody;
  /** deprecated use `other.collider` instead */
  collider: RapierCollider;
  /** deprecated use `other.rigidBodyObject` instead */
  rigidBodyObject?: Object3D;
  /** deprecated use `other.colliderObject` instead */
  colliderObject?: Object3D;
};
```

Keep backward compatibility with `@deprecated` tag so this is not a breaking change.

### CODE REVIEW

**Comment by wiledal** [comment]
This is nice!
In the future we should probably rename this to something like `source`, and `target`.

```tsx
onCollisionEnter(event => {
  console.log(event.source.collider) // this collider
  console.log(event.target.collider) // other collider
})
```

Although, `target` might be a confusing name since it is used by JavaScript for the source of the event...

**Comment by RodrigoHamuy** [comment]
I like the following. If you are happy I can update this PR or prep a new one for further discussion as it will become a breaking change.
```tsx
export type BaseCollisionPayload = {
  target: {
    rigidBody?: RapierRigidBody;
    collider: RapierCollider;
    rigidBodyObject?: Object3D;
    colliderObject?: Object3D;
  },
  other: {
    rigidBody?: RapierRigidBody;
    collider: RapierCollider;
    rigidBodyObject?: Object3D;
    colliderObject?: Object3D;
  },
}
```

**Comment by wiledal** [comment]
I think let's go for that! This library comes with the WIP disclosure, so breaking changes can happen. 
In that case change the changeset to `minor`, and update the docs!

We could also `...other` on the payload, and mark it as `@deprecated`, to allow both versions as an intermediate solution.
This is also nice as it lets us detect the affected collider of a RigidBody without needing to set individual events on each.

**Comment by RodrigoHamuy** [comment]
@wiledal updated.

**Pull request merged**
