### PR TITLE
Add vercel.json

### PR DESCRIPTION
**Pull request by hmans**
This adds a vercel configuration file that does two things, in order of importance:

- rewrite all paths to the demo app (not just `/`)
- silence GitHub notifications for new deployes (remove if you actually want them)

I'm not familiar with your Vercel configuration, so it's possible that you need to move this file somewhere else, but by default Vercel looks for it at the root of the deployed repository.

### CODE REVIEW

**Comment by wiledal** [comment]
Great stuff!

**Comment by wiledal** [comment]
I wonder if this will deploy actually, since you might need to be a developer on the target Vercel Team for it to accept it?

**Comment by hmans** [comment]
> I wonder if this will deploy actually, since you might need to be a developer on the target Vercel Team for it to accept it?

Not sure I understand the question. This is just meant as a fix so URLs like

https://react-three-rapier.pmnd.rs/kinematics

don't 404.

(I'm assuming that the examples app is being deployed to Vercel. Was this wrong?)

**Comment by wiledal** [comment]
The config is great, but the deployment fails due to it coming from a non-authed user. I am also not added to this project on Vercel, so I'm not sure if this will be accepted by Vercel's deployment bot, unless it is accepted by @drcmda.

**Comment by isaac-mason** [comment]
I've approved the deployment now! 🙂

**Comment by isaac-mason** [comment]
And the URL rewrite works 👌

**Pull request merged**
