### PR TITLE
fix: update dependencies, normalize testing

### PR DESCRIPTION
**Pull request by wiledal**
## Description

- Update some high-level dependencies
- Update test suite dependencies location
- ~Add .yarnrc.yml to support yarn 4~ 
  - This is the recommended way to go, but not supported on Vercel, so let's skip for now

### Problems with this update:
- r3/rapier in 'independent' stepping mode, relies on `requestAnimationFrame`, which breaks testing when running tests outside of a browser environment
  - We solve this by running tests with the `happy-dom` or `jsdom` environment
- New versions of `three-stdlib` (common dependency in all r3/* libs) has a `lottiejs` implementation which is optimized for ssr, and does some canvas operations immediately when run in a browser environment. This breaks tests.
  - To fix this, we can run in `jsdom`, and apply `vitest-canvas-mock` in the setup-file
- Unfortunately, for some reason, the Vercel deployment of the `demo` breaks when updating any of these libraries.
  - Switching from `happy-dom` to `jsdom` breaks Vercel deployment
  - Updating `vitest` to the latest version breaks Vercel deployment

As I personally don't have access to the Vercel deployment logs or settings, it's nearly impossible to replicate. It's very odd that the testing suite, which is not even run on Vercel, would be affecting the deployment.

Further work is needed to make this up to date with current versions of all the dependent software.

### Type of change

- 📦 Other (tests, refactoring, docs, etc.)

### Checklist:

- [x] 🔍 I have performed a self-review of my code
- [x] 🟢 All new and existing unit tests pass

### CODE REVIEW

**Comment by wiledal** [comment]
⭐ Update 
I cloned the repo and tried reproducing the issue. Out of the box, the demo does not build.
I solved it by setting the install script to `cd ../; yarn`, so that the install happens on the workspace root rather than in the demo itself.

Since I don't have access to the pmndrs Vercel account, I cannot check to see what's up, but it might be related.

**Comment by isaac-mason** [comment]
Hey @wiledal I can help with vercel debugging!

Looks like the last build failed on this:

```
[2/4] Fetching packages...
error jsdom@24.0.0: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Command "yarn install" exited with 1
```

**Comment by isaac-mason** [comment]
I'll try updating the node.js version in vercel and re-running 🙁

**Comment by isaac-mason** [comment]
ok, now the vercel deployment is up to a new error

```
🎁 error @react-three/rapier An unhandled Rollup error occurred: packages/react-three-rapier/src/utils/utils-collider.ts (2:7) Error when using sourcemap for reporting an error: Can't resolve original location of error.
🎁 info If want to learn more about the above error, check https://preconstruct.tools/errors
🎁 info If the error is not there and you want to learn more about it, open an issue at https://github.com/preconstruct/preconstruct/issues/new
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn build && cd demo && npx vite build" exited with 1
```

**Comment by wiledal** [comment]
Thanks @isaac-mason! I'm just back from a vacay 🌴. I'm trying to reproduce this error on Vercel on a forked repo. Could you let me know what the Vercel project's `Build & Development Settings`-settings are?

**Comment by isaac-mason** [comment]
Built and deployed successfully! https://react-three-rapier-jjahtxe68-pmndrs.vercel.app/

**Pull request merged**
